environment:
  CARGO_PATH: c:\users\appveyor\.cargo
  RUST_VERSION: 1.43.0
  S2PNG_COMMAND: target\debug\s2png.exe

cache:
  - '$(CARGO_PATH) -> appveyor.yml, Cargo.lock, Cargo.toml'

install:
  - cmd: appveyor-retry appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - cmd: rustup-init.exe --default-toolchain %RUST_VERSION% -y
  - cmd: set PATH=%CARGO_PATH%\bin;%PATH%

build_script:
  - cmd: cargo build

test_script:
  - cmd: cargo test

after_test:
  - cmd: copy %S2PNG_COMMAND% s2png.exe

artifacts:
  - path: s2png.exe
