name: CI
on: [push, pull_request]

env:
  S2PNG_COMMAND: target/debug/s2png

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      run: |
        cargo build

        cargo test
        cargo test -- --ignored
